### ISSUE TITLE
Surelog fails to build becuase cmake is confused about Python version

### ISSUE THREAD

**Issue by hzeller** [SymbiFlow/conda-packages#105]
https://travis-ci.com/github/SymbiFlow/conda-packages/jobs/349642231#L3447

[Installs Python (gets 3.7.6)](https://travis-ci.com/github/SymbiFlow/conda-packages/jobs/349642231#L3582), later in cmake it has trouble finding it. In fact is claims it finds it, but then also not...

This might be an issue with conflicting Python versions on the build system ? Is there something that needs to be done to have cmake be more robust, or does the CI environment be changed ?

```
CMake Error at /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
3777  Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) (found
3778  suitable version "3.7", minimum required is "3.3")
3779Call Stack (most recent call first):
3780  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
3781  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPython/Support.cmake:2398 (find_package_handle_standard_args)
3782  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPython3.cmake:311 (include)
3783  CMakeLists.txt:45 (find_package)
```

**Comment by hzeller** [comment]
Tomasz, is this something you see what needs to be fixed ?

**Comment by tgorochowik** [comment]
@hzeller I took a log at the differences in logs when it started to fail and in my opinion it failed after adding Windows support to surelog. This change seems to be the culprit:
https://github.com/alainmarcel/Surelog/commit/e63ebbecd#diff-af3b638bc2a3e6c650974192a53c7291R45-R50

@hs-apotell I think you are the author of this. Could you please take a look? I am afraid that simply reverting it may break Windows support.

**Comment by tgorochowik** [comment]
On the other hand I just realized that we successfully build a newer version (I think) of surelog in the uhdm-integration package. After taking a quick look it seems that the python requirement is in another section in meta.yml. We may want to check that (or see if the build flags used there are different than the flags in the vanilla surelog package). Maybe we can get this to work without changing the cmake files in surelog.
