### ISSUE TITLE
Slang currently fails building

### ISSUE THREAD

**Issue by hzeller** [SymbiFlow/conda-packages#64]
Here is an example run
https://travis-ci.com/SymbiFlow/conda-packages/jobs/275491438

**Comment by MikePopoloski** [comment]
Would be nice if this was fixed. It looks like your local patch for the static build doesn't apply cleanly anymore? Also slang now sets the output binary name of the driver project to "slang" instead of just "driver" so I believe build.sh won't find the binary correctly.

**Comment by mithro** [comment]
Have a fix in progress at https://github.com/mithro/litex-conda/commit/af03ac93ec0a3fa4127dcef9a31a365cf24a8207

**Comment by mithro** [comment]
WIP at https://github.com/SymbiFlow/conda-packages/pull/66
